name: Update Latest Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # Update every 24 hours
  workflow_dispatch:  # Allows manual triggering
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install github-readme-stats

      - name: Update README
        run: |
          npx github-readme-stats --username Raz-Saad --layout vertical --exclude forks > updated_repos.md
          sed -i '/<!--START_SECTION:repos-->/, /<!--END_SECTION:repos-->/d' README.md
          sed -i "/<!--END_SECTION:repos-->/i $(cat updated_repos.md)" README.md
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m 'Update latest repositories'
          git push
