name: Update Latest Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # Update every 24 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch latest repositories
        run: |
          gh repo list Raz-Saad --limit 5 --json name,url --jq '.[] | "* [" + .name + "](" + .url + ")"' > updated_repos.md

      - name: Update README
        run: |
          awk '/<!--START_SECTION:repos-->/ {print; in_section=1; next} /<!--END_SECTION:repos-->/ {print; in_section=0} !in_section' README.md > temp_readme.md
          cat updated_repos.md >> temp_readme.md
          echo "<!--END_SECTION:repos-->" >> temp_readme.md
          mv temp_readme.md README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m 'Update latest repositories'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
